### ISSUE TITLE
Key words extraction

### ISSUE THREAD

**Issue by ZuzannaKozyra** [ZuzannaKozyra/Womens_clothing_reviews#1]
Rzeczy związane ze słowami kluczowymi:

- [x] znalezienie metody/konkretnej biblioteki
- [x] analiza rzeczowników, czasowników, przymiotników, fraz

**Comment by ZuzannaKozyra** [comment]
[key_words_simple.zip](https://github.com/ZuzannaKozyra/Womens_clothing_reviews/files/14806692/key_words_simple.zip)
Wstępne wykresy, próba pracy z udpipe

**Comment by mlysakowski** [comment]
pierwsze podejscie do budowy modelu 
[projekt_eksploracja.zip](https://github.com/ZuzannaKozyra/Womens_clothing_reviews/files/15025483/projekt_eksploracja.zip)
